# Generated by Django 3.1.4 on 2020-12-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='StockSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_long_business_summary', models.CharField(max_length=100000000000000)),
                ('stock_pub_date', models.DateTimeField(verbose_name='date published')),
                ('stock_profit_margins', models.IntegerField(default=0)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockdashboard.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockdashboard.stock')),
            ],
        ),
    ]
