# Generated by Django 3.1.4 on 2020-12-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockchart',
            old_name='stock_id',
            new_name='stock_name',
        ),
        migrations.RenameField(
            model_name='stocksummary',
            old_name='stock_id',
            new_name='stock_name',
        ),
    ]
