# Generated by Django 3.1.4 on 2020-12-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdashboard', '0002_auto_20201224_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='', max_length=400),
        ),
    ]
